/* Curated MCP server catalog - fallback when mcp.so API requires auth */
/* Based on popular MCP servers from mcp.so */

export const CURATED_MCP_SERVERS = [
  {
    id: 'filesystem',
    name: 'Filesystem',
    icon: '📁',
    description: 'Secure file operations with configurable access controls. Read, write, list, and manage files and directories.',
    category: 'Developer Tools',
    tags: ['files', 'filesystem', 'local', 'secure'],
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-filesystem', '/allowed/path'],
    env: {},
    stars: 1200,
    verified: true,
  },
  {
    id: 'git',
    name: 'Git',
    icon: '📝',
    description: 'Git repository operations - read files, show commits, diff, status, log, and more.',
    category: 'Developer Tools',
    tags: ['git', 'version-control', 'repository'],
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-git'],
    env: {},
    stars: 950,
    verified: true,
  },
  {
    id: 'github',
    name: 'GitHub',
    icon: '🐙',
    description: 'GitHub API integration - manage repos, issues, PRs, actions, and more.',
    category: 'Developer Tools',
    tags: ['github', 'api', 'issues', 'prs'],
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-github'],
    env: { GITHUB_PERSONAL_ACCESS_TOKEN: '' },
    stars: 1500,
    verified: true,
  },
  {
    id: 'postgres',
    name: 'PostgreSQL',
    icon: '🐘',
    description: 'PostgreSQL database operations - query, schema inspection, migrations.',
    category: 'Databases',
    tags: ['postgres', 'database', 'sql', 'queries'],
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-postgres'],
    env: { POSTGRES_CONNECTION_STRING: '' },
    stars: 800,
    verified: true,
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    icon: '💾',
    description: 'SQLite database operations - query and manage local SQLite databases.',
    category: 'Databases',
    tags: ['sqlite', 'database', 'sql', 'local'],
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sqlite', '--db-path', './data.db'],
    env: {},
    stars: 600,
    verified: true,
  },
  {
    id: 'brave-search',
    name: 'Brave Search',
    icon: '🔍',
    description: 'Web search via Brave Search API - fast, privacy-focused search results.',
    category: 'Search',
    tags: ['search', 'web', 'brave', 'api'],
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-brave-search'],
    env: { BRAVE_API_KEY: '' },
    stars: 700,
    verified: true,
  },
  {
    id: 'fetch',
    name: 'Fetch',
    icon: '📥',
    description: 'HTTP fetch capabilities - make web requests, fetch content from URLs.',
    category: 'Developer Tools',
    tags: ['http', 'fetch', 'web', 'api'],
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-fetch'],
    env: {},
    stars: 550,
    verified: true,
  },
  {
    id: 'memory',
    name: 'Memory',
    icon: '🧠',
    description: 'Persistent memory for AI agents - store and retrieve information across sessions.',
    category: 'Memory & Knowledge',
    tags: ['memory', 'knowledge', 'persistent', 'agent'],
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    env: {},
    stars: 900,
    verified: true,
  },
  {
    id: 'sequential-thinking',
    name: 'Sequential Thinking',
    icon: '🤔',
    description: 'Structured thinking process - break down complex problems into steps.',
    category: 'Agent Workflows',
    tags: ['thinking', 'reasoning', 'agent', 'workflow'],
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sequential-thinking'],
    env: {},
    stars: 1100,
    verified: true,
  },
  {
    id: 'time',
    name: 'Time',
    icon: '🕐',
    description: 'Time and timezone operations - current time, formatting, conversions.',
    category: 'Utilities',
    tags: ['time', 'date', 'timezone', 'utility'],
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-time'],
    env: {},
    stars: 300,
    verified: true,
  },
  {
    id: 'everything',
    name: 'Everything (Reference)',
    icon: '📦',
    description: 'Reference server demonstrating all MCP capabilities - resources, tools, prompts.',
    category: 'Developer Tools',
    tags: ['reference', 'demo', 'all-capabilities'],
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-everything'],
    env: {},
    stars: 2000,
    verified: true,
  },
  {
    id: 'aws',
    name: 'AWS',
    icon: '☁️',
    description: 'AWS cloud operations - EC2, S3, Lambda, DynamoDB, and more.',
    category: 'Cloud & Infrastructure',
    tags: ['aws', 'cloud', 'infrastructure', 'devops'],
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-aws'],
    env: { AWS_ACCESS_KEY_ID: '', AWS_SECRET_ACCESS_KEY: '', AWS_REGION: '' },
    stars: 650,
    verified: true,
  },
  {
    id: 'docker',
    name: 'Docker',
    icon: '🐳',
    description: 'Docker container management - containers, images, networks, volumes.',
    category: 'Developer Tools',
    tags: ['docker', 'containers', 'devops'],
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-docker'],
    env: {},
    stars: 500,
    verified: true,
  },
  {
    id: 'slack',
    name: 'Slack',
    icon: '💬',
    description: 'Slack workspace integration - channels, messages, users, files.',
    category: 'Communication',
    tags: ['slack', 'messaging', 'team', 'communication'],
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-slack'],
    env: { SLACK_BOT_TOKEN: '', SLACK_TEAM_ID: '' },
    stars: 450,
    verified: true,
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    icon: '☁️',
    description: 'Google Drive file operations - list, read, write, search files.',
    category: 'Files & Storage',
    tags: ['google-drive', 'files', 'storage', 'google'],
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-gdrive'],
    env: { GOOGLE_CLIENT_ID: '', GOOGLE_CLIENT_SECRET: '', GOOGLE_REFRESH_TOKEN: '' },
    stars: 400,
    verified: true,
  },
  {
    id: 'postman',
    name: 'Postman',
    icon: '📮',
    description: 'Postman API testing - collections, environments, requests.',
    category: 'Developer Tools',
    tags: ['postman', 'api', 'testing', 'http'],
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-postman'],
    env: { POSTMAN_API_KEY: '' },
    stars: 350,
    verified: false,
  },
]

export const MCP_CATEGORIES = [
  'All',
  'Developer Tools',
  'Databases',
  'Search',
  'Memory & Knowledge',
  'Agent Workflows',
  'Utilities',
  'Cloud & Infrastructure',
  'Files & Storage',
  'Communication',
]