/* Curated skills catalog - fallback when external APIs require auth */
/* Based on popular skills from skills.sh leaderboard */

export const CURATED_SKILLS = [
  {
    id: 'find-skills',
    name: 'Find Skills',
    icon: '🔍',
    description: 'Helps users discover and install agent skills when they ask questions like "how do I do X", "find a skill for X", or express interest in extending capabilities.',
    tags: ['agent-workflows', 'discovery'],
    brief: `Skill: FIND SKILLS. Help users discover and install agent skills.\n- When users ask "how do I do X", "find a skill for X", "is there a skill that can...", use this skill to search for relevant skills.\n- Suggest relevant skills from the catalog and explain how to install them.\n- Always check if a skill exists before building custom solutions.`,
    source: 'skills.sh',
    installs: 3500000,
  },
  {
    id: 'grill-me',
    name: 'Grill Me',
    icon: '🔥',
    description: 'A relentless interview to sharpen a plan or design. Challenges assumptions and pushes for clarity.',
    tags: ['design', 'planning', 'critique'],
    brief: `Skill: GRILL ME. Conduct a rigorous interview to sharpen plans and designs.\n- Ask probing questions that expose weak assumptions and unclear requirements.\n- Challenge every design decision: "Why this approach?", "What are the alternatives?", "What could go wrong?".\n- Push for specific, measurable success criteria.\n- Don't accept vague answers - drill down until the plan is concrete and defensible.\n- Output a refined plan with risks, alternatives, and clear next steps.`,
    source: 'skills.sh',
    installs: 1200000,
  },
  {
    id: 'frontend-design',
    name: 'Frontend Design',
    icon: '🎨',
    description: 'Guidance for distinctive, intentional visual design when building new UI or reshaping an existing one. Helps with aesthetic direction, typography, and making choices that don\'t read as templated defaults.',
    tags: ['design', 'ui', 'css', 'typography'],
    brief: `Skill: FRONTEND DESIGN. Create distinctive, intentional visual designs.\n- Avoid templated defaults - every design choice should be intentional.\n- Establish a clear typographic scale (headings, body, captions) with consistent line heights.\n- Choose a cohesive color palette with semantic roles (primary, secondary, accent, surface, text).\n- Use spacing systems (4px/8px grid) rather than arbitrary values.\n- Design for states: hover, focus, active, disabled, loading, empty, error.\n- Ensure accessibility: contrast ratios, focus indicators, semantic HTML.\n- Prefer CSS variables for theming and dark mode support.`,
    source: 'skills.sh',
    installs: 908000,
  },
  {
    id: 'vercel-react-best-practices',
    name: 'Vercel React Best Practices',
    icon: '⚡',
    description: 'React and Next.js performance optimization guidelines from Vercel Engineering. Use when writing, reviewing, or refactoring React/Next.js code.',
    tags: ['react', 'nextjs', 'performance', 'development'],
    brief: `Skill: VERCEL REACT BEST PRACTICES. Write performant React/Next.js code.\n- Use Server Components by default; Client Components only when needed (interactivity, hooks, browser APIs).\n- Optimize data fetching: parallel where possible, use Suspense boundaries, avoid waterfalls.\n- Use \`next/image\` for automatic optimization; specify width/height to prevent layout shift.\n- Minimize bundle size: dynamic imports for heavy components, tree-shake dependencies.\n- Prefer CSS Modules or Tailwind over CSS-in-JS for zero-runtime styling.\n- Use \`useMemo\`/\`useCallback\` only for measured hotspots - profile first.\n- Enable React Compiler (when stable) for automatic memoization.\n- Test with real-world data volumes, not toy datasets.`,
    source: 'skills.sh',
    installs: 732000,
  },
  {
    id: 'agent-browser',
    name: 'Agent Browser',
    icon: '🌐',
    description: 'Browser automation CLI for AI agents. Use when the user needs to interact with websites, including navigating pages, filling forms, clicking buttons, taking screenshots, extracting data, testing web apps, or automating any browser task.',
    tags: ['agent-workflows', 'browser', 'automation', 'testing'],
    brief: `Skill: AGENT BROWSER. Automate browser tasks programmatically.\n- Use for: navigating pages, filling forms, clicking buttons, taking screenshots, extracting data, testing web apps.\n- Install: \`npm i -D @vercel-labs/agent-browser\`\n- Prefer over built-in browser automation - handles complex scenarios (SPA navigation, auth, iframes).\n- Supports Vercel Sandbox microVMs for cloud execution.\n- Can automate Electron apps (VS Code, Slack, Discord, Figma, Notion, Spotify).\n- Use for exploratory testing, dogfooding, QA, bug hunts, app quality reviews.`,
    source: 'skills.sh',
    installs: 900000,
  },
  {
    id: 'accessibility',
    name: 'Accessibility',
    icon: '♿',
    description: 'Semantic HTML, keyboard navigation, visible focus, ARIA only where needed, WCAG AA contrast.',
    tags: ['a11y', 'inclusive', 'quality'],
    brief: `Skill: ACCESSIBILITY. Build to WCAG 2.1 AA.\n- Use semantic elements (button, nav, main, label, heading order) before reaching for ARIA; add ARIA only when a native element cannot express the state.\n- Every interactive element is reachable and operable by keyboard, with a visible focus ring (never remove outline without a replacement).\n- Form inputs have associated <label>s; errors are announced (aria-invalid, aria-describedby).\n- Images carry alt text (empty alt="" for decorative). Maintain a contrast ratio of at least 4.5:1 for body text.\n- Respect prefers-reduced-motion by toning down animation.`,
    source: 'builtin',
    installs: 0,
  },
  {
    id: 'responsive',
    name: 'Responsive Layout',
    icon: '📱',
    description: 'Mobile-first fluid layouts, sensible breakpoints, no horizontal scroll, touch-friendly targets.',
    tags: ['mobile', 'layout', 'css'],
    brief: `Skill: RESPONSIVE LAYOUT. Design mobile-first.\n- Base styles target small screens; layer larger layouts with min-width breakpoints (sm/md/lg/xl). Prefer fluid units (%, fr, clamp(), min()/max()) over fixed pixels.\n- No horizontal scrolling at any width. Long words and code wrap or scroll within their own container.\n- Grids collapse to a single column on narrow screens; navigation becomes a drawer or stacked menu.\n- Interactive targets are at least 40x40px with comfortable spacing for touch.\n- Test mentally at 375px, 768px and 1280px before finishing.`,
    source: 'builtin',
    installs: 0,
  },
  {
    id: 'forms-validation',
    name: 'Forms & Validation',
    icon: '✅',
    description: 'Controlled inputs, inline validation, clear error and success states, disabled-while-submitting.',
    tags: ['forms', 'ux', 'validation'],
    brief: `Skill: FORMS & VALIDATION.\n- Inputs are controlled; validate on blur and on submit, showing inline field-level errors next to the offending input, plus a summary for the whole form when useful.\n- Disable the submit button and show a pending state while a request is in flight; re-enable and surface server errors on failure.\n- Mark required fields, use appropriate input types (email, tel, number, password) and autocomplete hints.\n- Show a clear success confirmation. Never lose the user's typed values on a validation failure.`,
    source: 'builtin',
    installs: 0,
  },
  {
    id: 'loading-states',
    name: 'Loading & Empty States',
    icon: '⏳',
    description: 'Skeletons, spinners, error fallbacks and empty states for every async view.',
    tags: ['ux', 'async', 'polish'],
    brief: `Skill: LOADING & EMPTY STATES. Every async view handles all four states.\n- Loading: skeletons that match the final layout (preferred) or a spinner; never a blank screen.\n- Empty: a friendly, actionable empty state that explains what goes there and how to add the first item.\n- Error: a readable message with a retry action; never dump a raw stack trace on the user.\n- Success: the real content. Keep transitions between states smooth and avoid layout shift.`,
    source: 'builtin',
    installs: 0,
  },
  {
    id: 'motion',
    name: 'Motion & Animation',
    icon: '✨',
    description: 'Purposeful transitions, keyframes and micro-interactions that respect prefers-reduced-motion.',
    tags: ['animation', 'polish', 'css'],
    brief: `Skill: MOTION & ANIMATION. Add motion with intent, not decoration.\n- Animate state changes the user should notice: hover/active affordances, enter/exit of lists and modals, value changes, loading progress.\n- Prefer transform and opacity (composited, cheap) over animating layout properties. Keep durations short (~120–300ms) with natural easing.\n- Wrap non-essential motion in a prefers-reduced-motion media query that reduces or removes it.\n- For complex sequences reach for a library (framer-motion) and install it before importing.`,
    source: 'builtin',
    installs: 0,
  },
  {
    id: 'dark-mode',
    name: 'Dark Mode',
    icon: '🌗',
    description: 'Theme tokens, a toggle, system-preference default and persisted choice.',
    tags: ['theme', 'dark', 'css'],
    brief: `Skill: DARK MODE. Support light and dark themes.\n- Define color tokens once (CSS variables in an @theme block or :root) and consume them everywhere; never hardcode hex values in components.\n- Provide a theme toggle; default to the user's system preference (prefers-color-scheme) and persist an explicit choice to localStorage.\n- Ensure both themes meet contrast requirements — dark mode is not just inverted colors; adjust surface elevation and accent tones per theme.`,
    source: 'builtin',
    installs: 0,
  },
  {
    id: 'data-fetching',
    name: 'Data Fetching',
    icon: '🔌',
    description: 'Clean async data patterns: caching, retries, request cancellation and typed responses.',
    tags: ['data', 'api', 'async'],
    brief: `Skill: DATA FETCHING. Handle remote data robustly.\n- Centralize fetching (a small api client or TanStack Query) rather than scattering raw fetch calls through components; install the library before importing it.\n- Type responses with TypeScript interfaces. Handle network errors, non-2xx statuses and timeouts.\n- Cancel or ignore stale requests when a component unmounts or params change (AbortController) to avoid race conditions and state updates after unmount.\n- Cache where it helps and show the loading/error states described by the Loading & empty states skill.`,
    source: 'builtin',
    installs: 0,
  },
  {
    id: 'state-management',
    name: 'State Management',
    icon: '🗂️',
    description: 'Right-size state: local first, lift only when shared, reach for a store only when it earns its place.',
    tags: ['architecture', 'state', 'react'],
    brief: `Skill: STATE MANAGEMENT. Keep state as local and simple as possible.\n- Start with component-local state; lift to the nearest common parent only when two components truly share it.\n- Derive values during render instead of duplicating them into state. Keep server data (fetched) separate from UI state.\n- Introduce context for cross-cutting concerns (theme, auth, current user) and a store like Zustand only when prop-drilling becomes genuinely painful — do not start there.\n- Colocate state with the components that use it and avoid one giant global object.`,
    source: 'builtin',
    installs: 0,
  },
  {
    id: 'performance',
    name: 'Performance',
    icon: '⚡',
    description: 'Code splitting, lazy routes, memoization where it matters, and optimized images.',
    tags: ['performance', 'optimization', 'react'],
    brief: `Skill: PERFORMANCE. Ship something that stays fast as it grows.\n- Lazy-load routes and heavy components (React.lazy + Suspense) so the initial bundle stays small.\n- Memoize only measured hotspots (React.memo, useMemo, useCallback) — do not wrap everything; premature memoization adds complexity for no gain.\n- Optimize images: correct sizing, modern formats, lazy-load below-the-fold media.\n- Avoid layout thrash and unnecessary re-renders; keep lists keyed with stable ids. Prefer CSS for animation.`,
    source: 'builtin',
    installs: 0,
  },
  {
    id: 'data-viz',
    name: 'Charts & Data Viz',
    icon: '📊',
    description: 'Responsive, accessible charts with recharts, plus a tabular fallback for the underlying data.',
    tags: ['charts', 'analytics', 'recharts'],
    brief: `Skill: CHARTS & DATA VISUALIZATION.\n- Use a charting library (recharts is a good default) and install it before importing.\n- Charts are responsive (fill their container) and themed to match the app's tokens, with clear axes, legends, units and tooltips.\n- Do not rely on color alone to encode meaning; provide an accessible table fallback or aria labels for the data.\n- Handle empty and single-point datasets gracefully instead of rendering a broken axis.`,
    source: 'builtin',
    installs: 0,
  },
  {
    id: 'seo-metadata',
    name: 'SEO & Metadata',
    icon: '🔍',
    description: 'Document titles, meta descriptions, semantic headings and Open Graph tags per route.',
    tags: ['seo', 'metadata', 'marketing'],
    brief: `Skill: SEO & METADATA.\n- Set a descriptive document title and meta description per route/view; keep headings in a single logical hierarchy (one h1, no skipped levels).\n- Add Open Graph and Twitter card tags for shareable pages, and a canonical URL where relevant.\n- Use descriptive, human-readable route paths and meaningful link text (not "click here").\n- Provide alt text for images and ensure the page renders meaningful content without client-side-only tricks that crawlers miss.`,
    source: 'builtin',
    installs: 0,
  },
  {
    id: 'testing',
    name: 'Testing',
    icon: '🧪',
    description: 'Vitest + Testing Library: behavior-focused component tests and a repeatable test command.',
    tags: ['testing', 'quality', 'vitest'],
    brief: `Skill: TESTING. Add tests that describe behavior, not implementation.\n- Use Vitest with @testing-library/react and @testing-library/user-event; install them (and jsdom) as dev dependencies before importing.\n- Query by role/label/text the way a user finds elements; assert on visible outcomes and accessible states rather than internal details.\n- Cover the critical paths: rendering, user interaction, validation and error handling. Keep tests fast and independent.\n- Add a "test" script to package.json and make sure the suite passes before finishing.`,
    source: 'builtin',
    installs: 0,
  },
  {
    id: 'self-learning',
    name: 'Self-Learning Agent',
    icon: '🧠',
    description: 'Enables the agent to learn from its interactions, remember patterns, and improve over time by storing successful patterns and solutions.',
    tags: ['learning', 'memory', 'agent', 'improvement', 'adaptive'],
    brief: `Skill: SELF-LEARNING AGENT. Enable continuous improvement through learning.\n- Store successful code patterns, solutions, and architectural decisions in a persistent knowledge base.\n- When encountering similar problems, retrieve and apply previously successful solutions.\n- Track which approaches work well for specific project types, frameworks, or problem domains.\n- Learn user preferences: coding style, naming conventions, architectural patterns.\n- Maintain a local knowledge file (.lovable-learnings.json) in the project root that persists across sessions.\n- Before starting a new task, check the knowledge base for relevant patterns.\n- After completing a task successfully, extract and store the key patterns used.\n- Learn from failures too: record what didn't work and why to avoid repeating mistakes.\n- Provide a "learning summary" at the end of each session showing what was learned.\n- Respect privacy: all learning data stays local in the project directory.\n- Allow users to review, edit, or clear the learning database at any time.`,
    source: 'builtin',
    installs: 0,
  },
]