/**
 * Mock provider — NOT a real model.
 *
 * Exists so the agent loop (streaming, tool dispatch, tool results, git
 * commit, SSE events) can be verified deterministically without spending API
 * tokens. Selecting it in the UI shows a warning banner; anything it "builds"
 * is scripted and should never be mistaken for model output.
 */
const PROBE_COMPONENT = `export function AgentProbe({ label = 'tool loop verified' }: { label?: string }) {
  return (
    <div className="rounded-lg border border-emerald-400/30 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-200">
      {label}
    </div>
  )
}
`

function chunk(text, onText, size = 24) {
  for (let i = 0; i < text.length; i += size) {
    onText?.(text.slice(i, i + size))
  }
}

export async function streamMock({ messages = [], onText, onThinking, onToolStart, signal }) {
  if (signal?.aborted) throw new Error('Aborted')

  const sawToolResult = messages.some(
    (m) => Array.isArray(m.content) && m.content.some((b) => b.type === 'tool_result'),
  )

  await new Promise((resolve) => setTimeout(resolve, 120))

  if (!sawToolResult) {
    const thinking = 'The user wants to verify the tool loop. I will create a single small probe component under src/components/, write it with write_file, then stop and summarise. No dependencies are needed.'
    chunk(thinking, onThinking, 18)
    const text = 'This is the mock provider. It writes one probe file so the tool loop can be verified, then stops.'
    chunk(text, onText)

    const call = {
      id: `mock_${Date.now()}`,
      name: 'write_file',
      args: { path: 'src/components/AgentProbe.tsx', content: PROBE_COMPONENT },
    }
    onToolStart?.({ id: call.id, name: call.name })

    return {
      provider: 'mock',
      model: 'mock-scripted',
      text,
      thinking,
      toolCalls: [call],
      stopReason: 'tool_calls',
      usage: { inputTokens: 0, outputTokens: 0 },
      mock: true,
    }
  }

  const thinking = 'The probe file was written successfully. Nothing else is required, so I will confirm completion.'
  chunk(thinking, onThinking, 18)
  const text = 'Mock turn complete: wrote src/components/AgentProbe.tsx. No real model was called.'
  chunk(text, onText)

  return {
    provider: 'mock',
    model: 'mock-scripted',
    text,
    thinking,
    toolCalls: [],
    stopReason: 'stop',
    usage: { inputTokens: 0, outputTokens: 0 },
    mock: true,
  }
}

export const MOCK_WARNING = 'Mock provider active — output is scripted, not generated by a model.'
